# Generated by Django 6.0.5 on 2026-05-25 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_plant_code', models.CharField(blank=True, default='', max_length=20)),
                ('utility_account_number', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='DataUploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Procurement'), ('UTILITY', 'Utility Bill'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_jobs', to='api.tenant')),
            ],
            options={
                'db_table': 'data_upload_jobs',
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SCOPE1', 'Scope 1 - Direct Emissions'), ('SCOPE2', 'Scope 2 - Indirect Energy'), ('SCOPE3', 'Scope 3 - Value Chain')], max_length=10)),
                ('category', models.CharField(choices=[('FUEL', 'Fuel Combustion'), ('ELECTRICITY', 'Purchased Electricity'), ('FLIGHT', 'Business Flight'), ('HOTEL', 'Hotel Stay'), ('GROUND', 'Ground Transport'), ('OTHER', 'Other')], max_length=20)),
                ('source_type', models.CharField(max_length=20)),
                ('raw_payload', models.JSONField()),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('original_value', models.FloatField(blank=True, null=True)),
                ('original_unit', models.CharField(blank=True, default='', max_length=20)),
                ('normalized_value', models.FloatField(blank=True, null=True)),
                ('normalized_unit', models.CharField(blank=True, default='', max_length=20)),
                ('normalized_co2_kg', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved for Audit'), ('FLAGGED', 'Flagged - Needs Review'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('analyst_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('upload_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.datauploadjob')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.facility')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='api.tenant')),
            ],
            options={
                'db_table': 'emission_records',
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='api.tenant'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Record Created'), ('UPDATED', 'Record Updated'), ('APPROVED', 'Record Approved'), ('FLAGGED', 'Record Flagged'), ('REJECTED', 'Record Rejected'), ('NOTE_ADDED', 'Analyst Note Added')], max_length=20)),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emission_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.emissionrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.tenant')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_unit', models.CharField(max_length=20)),
                ('target_unit', models.CharField(max_length=20)),
                ('conversion_factor', models.FloatField()),
                ('category', models.CharField(default='mass', max_length=50)),
            ],
            options={
                'db_table': 'unit_conversions',
                'unique_together': {('source_unit', 'target_unit')},
            },
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'status'], name='emission_re_tenant__615123_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'source_type'], name='emission_re_tenant__7e3b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope'], name='emission_re_tenant__ec4786_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'emission_record'], name='audit_logs_tenant__f14a74_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'created_at'], name='audit_logs_tenant__0b1a88_idx'),
        ),
    ]
